# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8888
    
# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    redis:
      database: 5
      host: localhost
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

# static resources
    resources:
            static-locations: classpath:/static/,classpath:/views/
# freemarker       
    freemarker:
      template-loader-path: classpath:/fkTemplate/
      cache: false
      prefix: 
      suffix: .html
      charset: UTF-8
      content-type: text/html
    
#Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    
logging:
  level:
    io.renren: debug
security:
  basic:
    enabled: false